language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

## Non-sudo environments are faster
sudo: false

## Cache composer and vendor libraries
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

before_script:
  - travis_retry composer config github-oauth.github.com "${GITHUB_OAUTH_TOKEN}"
  - pecl install ast
  - echo "${TRAVIS_PHP_VERSION}"

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover tests/clover.xml
  -
  - composer require wata727/pahout
  - vendor/bin/pahout --php-version 7.1.3
  - composer remove wata727/pahout
  -
  - composer require wapmorgan/php-code-fixer
  - vendor/bin/phpcf --target=7.1 --exclude=vendor .
  - composer remove wapmorgan/php-code-fixer

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
