name: Static analysis

on: [push, pull_request]

jobs:
  run:
    if: ${{ !startsWith(github.event.head_commit.message, 'Translation:') }}

    runs-on: ${{ matrix.operating-system }}

    strategy:
        matrix:
          operating-system: ['ubuntu-20.04']
          php-version: ['7.1', '7.2', '7.3', '7.4']

    name: phpstan

    steps:
      - uses: actions/checkout@v2

      - run: composer validate

      - run: composer global require phpstan/phpstan phpstan/extension-installer phpstan/phpstan-deprecation-rules phpstan/phpstan-strict-rules phpstan/phpstan-phpunit

      - run: composer install --no-progress

      - run: ~/.composer/vendor/bin/phpstan analyze --no-progress --level=max app modules_v4 index.php
